tasks:
  - name: utils
    before: |
      sudo apt-get install tree

  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh

  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh

vscode:
  extensions:
    - TabNine.tabnine-vscode
    - hashicorp.terraform
    - amazonwebservices.aws-toolkit-vscode
